### ISSUE TITLE
Why "updateInterval + Math.floor(Math.random() * 10000)"

### ISSUE THREAD

**Issue by sosus66** [Sinclair81/Homebridge-Logo-TS#13]
I've seen in your sources that you add random seconds to the updateInterval for use with setTimeout(() => {...}). 
Is it a performance issue to not set the interval directly to "updateInterval" (+ an offset of maybe some milliseconds) ?

I want to use the switch accessory in combination with a hardware input on my logo to detect a button press, but in the worst case I have to wait 10 seconds before the switch is updated in homebridge/homekit...

Thanks in advance!

**Comment by Sinclair81** [comment]
Yes, if all accessories want to talk to the logo at the same time, then there is very likely a problem.

If you have a new logo from 8.FS4 you can also use my new plug-in Homebridge-Logo-Platform. 
This only supports ModBus. 

If you are of course dependent on Snap7 (S7 protocol) for a Logo 0BA7 or 0BA8, 
I can also integrate an opt-out for the random seconds in the Logo-TS.

For explanation:

Logo-TS creates an independent accessory in the Homebridge from every config entry.

Logo platform creates a logo with its associated accessories. You don't see the logo itself in the Homebridge, but in the background it organizes the requests via ModBus for the correct logo. So everything goes much faster and the individual accessories cannot interfere with each other.

I have an 8.FS4 that I use as a HW bridge from ModBus to two other 0BA7. 
At the moment there are very few network inputs that get stuck on "1".

**Comment by Sinclair81** [comment]
Please try v1.3.0!
`"randomInterval": -1,` 

I will probably build Snap7 into Homebridge-Logo-Platform after all. 
Then you can also switch to the plugin.

**Comment by sosus66** [comment]
Thanks!!! I am watching your new plugin Homebridge-Logo-Platform already...
