### ISSUE TITLE
An error occurred during recv TCP -> homebride freezes

### ISSUE THREAD

**Issue by vincentcox** [Sinclair81/Homebridge-Logo-TS#2]
It seems that the homebridge instance freezes with this plugin when use the home app outside the network. Same happens also after a while when too many accessoires are being used at the same time.

We enabled debugging on a accessory and it throws the error "An error occurred during recv TCP":
```
Jan 17 13:55:43 hoobs hoobs[616]: [Homebridge] [1/17/2020, 1:55:43 PM] [Living Room Light] Switch ? true
Jan 17 13:56:21 hoobs hoobs[616]: [Homebridge] [1/17/2020, 1:56:21 PM] [Living Room Light] Set switch to false
Jan 17 13:56:21 hoobs hoobs[616]: [Homebridge] [1/17/2020, 1:56:21 PM] [Living Room Light] Set switch to false
Jan 17 13:56:30 hoobs hoobs[616]: [Homebridge] [1/17/2020, 1:56:30 PM] [Living Room Light]  >> DBRead failed. Code #655470 -  ISO : An error occurred during recv TCP : Connection timed out
Jan 17 13:56:30 hoobs hoobs[616]: [Homebridge] [1/17/2020, 1:56:30 PM] [Living Room Light]  >> DBWrite failed. Code #655470 -  ISO : An error occurred during recv TCP : Connection timed out
```

Any idea what is causing this and how we can solve this?

Thanks in advance and have a great weekend!

**Comment by Sinclair81** [comment]
Issues # 2 and # 3.
Sorry, but there is not much I can do about that. This is a communication problem from Snap7.
My solution for this is a LOGO! 8.SF4 that works as a ModBus / S7-400 bridge. For my last 2 LOGO! 0BA7.
