### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by YannickHaas** [Sinclair81/Homebridge-Logo-TS#3]
>> Connection failed. Code #655470 -  ISO : An error occurred during recv TCP : Connection timed out

What is the reason for this error. It is a infrequent one. Not specified to one accessory. 

Setting the updateInterval to different numbers isn't a solution.

May be it depends on to many request at the same time, between Homebridge and Logo?!

**Comment by Sinclair81** [comment]
Issues # 2 and # 3.
Sorry, but there is not much I can do about that. This is a communication problem from Snap7.
My solution for this is a LOGO! 8.SF4 that works as a ModBus / S7-400 bridge. For my last 2 LOGO! 0BA7.
