### ISSUE TITLE
Valve Type is not changeable

### ISSUE THREAD

**Issue by YannickHaas** [Sinclair81/Homebridge-Logo-TS#4]
// GENERIC_VALVE = 0; IRRIGATION = 1; SHOWER_HEAD = 2; WATER_FAUCET = 3;

Normally you can choose between one of these types, but it won't change in the home app.

**Comment by Sinclair81** [comment]
That's not exactly correct! ValveType 0, 2 and 3 have the same icon, a water tap. Only ValveType 1 has a different icon, a lawn sprinkler.
