### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by roelfoubert** [Sinclair81/Homebridge-Logo-TS#5]
I have a logo 8 SF4 but I can't get it to work. 
What do I need to add in my logo program?
Do I need to connect my homebridge as a modbus device?

**Comment by Sinclair81** [comment]
Ja, im Programm der LOGO! mußt du natürlich auch die Mod-Bus Adresse angeben.
"Extras" -> "Ethernet Verbindungen..." in der Liste dann einen rechts klick und "Server Verbindung hinzufügen" ->
"Modus-Verbindung" da dann den gewünschten Port eintragen (von 502 bis 507).
