### ISSUE TITLE
Control light with button and homebridge

### ISSUE THREAD

**Issue by roelfoubert** [Sinclair81/Homebridge-Logo-TS#6]
I want to combine the normal buttons in the house to control the lights with homebridge.
When I use the light block, I need to use the output brightness aand dimmer. 
But it is a simple on/off light. 
Homebridge doesn't get the correct state of the lightbulb when changing with the buttons and then with my smartphone.

This is my standard pulse relay without homebridge.
![Logo pulse relay](https://user-images.githubusercontent.com/9874656/100984811-7b287380-354b-11eb-9488-3b4aa1870e26.jpg)

**Comment by Sinclair81** [comment]
You should use a switch accessory for this. That has 3 connections to LOGO !.
1. to read
2. to set
3. to reset
In the LOGO! Folder is also a picture, as it is in LOGO! Program should look like.
