### ISSUE TITLE
Unable to read state of switch over Modbus

### ISSUE THREAD

**Issue by pyatnitsev** [Sinclair81/Homebridge-Logo-TS#7]
Hello!

I have an pulse relay on Logo! 
M1 connected to trig, and M2 connected right after Q1

I can swith on / off over Apple Home, but it seems can't get state of switch. I have connection timeout at homebridge log. 

```
```
![image](https://user-images.githubusercontent.com/4361764/106341736-59c7d780-62af-11eb-9b01-763d60198308.png)

What's can be wrong?

**Comment by Sinclair81** [comment]
Hi,
What did you specify for the accessory in the homebridge?
And what exactly does the LOGO program look like?
Can you please post a picture of both things.

**Comment by pyatnitsev** [comment]
Thanks for quick response.

On the Logo! side I have a little bit strange scheme:
![image](https://user-images.githubusercontent.com/4361764/106364760-8a0c8600-6342-11eb-99eb-18427bf763a3.png)

M51 for change state, and L6 (real swith) to change state too. 

On the HomeBrigde I have following:


If the light turned off and I switch it on by modbus - it works well, but if I turn it on by L6, it's does not effect on state in Apple home.

I will be happy, if you suggest me a way to manipulate my ligth over L-input and M-input as well, with correct state in apple home, e.g. if I clicked by real switch (L6), it's effects virtual switch state on Apple home. 

![image](https://user-images.githubusercontent.com/4361764/106365010-c12f6700-6343-11eb-8378-503eb1a3a871.png)

**Comment by Sinclair81** [comment]
The LOGO side looks good, but I would replace the XOR with a normal OR.
But in the settings for the Homebridge the setting updateInterval is missing. e.g. "updateInterval": 60000 - for one update per minute.

**Comment by pyatnitsev** [comment]
Thank you!
You're right, I forgot updateInterval, but it set it to 150ms to get more interactive behaviour. 
Also, thanks for suggestion about OR instead of XOR - XOR is not needed here.
