### ISSUE TITLE
Network input stays 1

### ISSUE THREAD

**Issue by roelfoubert** [Sinclair81/Homebridge-Logo-TS#9]
I have sometimes have a problem with the network inputs.
The networkinput stays high (1) so I cant change the status of the lights with the buttons in my house.
When I use apple home to turn the light on and off, the input resets and I can use my physical buttons.
Do you know how this problem can be solved?

**Comment by Sinclair81** [comment]
Yes, yesterday I had the same problem with my Test Home. With my LOGOs that really control the house, I haven't had these problems yet. There I set an "updateInterval" of 1 minute (60000ms) everywhere. However, if there is still space in the program for the LOGO, you can still switch an AND with edge evaluation after each network input.
<img width="674" alt="Bildschirmfoto 2021-02-01 um 22 56 55" src="https://user-images.githubusercontent.com/21153794/106523004-ce358d00-64e0-11eb-88f2-70cbde3407a7.png">
